language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install package
install:
  - python setup.py install

# command to run tests
script:
  - nosetests
  - image-scraper ananth.co.in/test.html
#after_success:
#  coveralls
notifications:
  email: false
