language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
#install: pip install -r requirements.txt --use-mirrors
install:
  - pip install ImageScraper
  - pip install future

# command to run tests
script:
  - nosetests
#after_success:
#  coveralls
notifications:
  email: false
