language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install package
install:
  - pip install setuptools --upgrade
  - pip install coveralls
  - python setup.py install
# command to run tests
script:
  - nosetests --with-coverage --cover-package=image_scraper
  - image-scraper ananth.co.in/test.html
after_success:
  coveralls
notifications:
  email: false
